export const projects = [
  {
    title: 'sdanundverkauf.de',
    description: "On this website any user can get up-to-date information about the current gold and silver prices and can decide if they want to sell their old gold or silver products to my client. There is also a calculator to help the user get an estimate of what they could get for their products before they actually go to the store.",
    image: '/images/6.png',
    tags: ['React.js', 'Next.js', 'PHP', 'styled-components'],
    code: 'https://github.com/mihaimazareanu/sdanundverkauf',
    visit: 'https://sdanundverkauf.de',
    id: 0,
  },
  {
    title: 'kidsFi',
    description: "kidsFi is a Next.js app that introduces children to finance. It allows them to track their piggy bank, savings account, and interest rate. Built with MongoDB, styled-components, and Figma, it's a simple and engaging way for kids to learn about personal finance.",
    image: '/images/4.png',
    tags: ['React.js', 'Next.js', 'MongoDB', 'styled-components'],
    code: 'https://github.com/mihaimazareanu/capstone-project-kidsfi',
    visit: 'https://kidsfi.vercel.app/',
    id: 1,
  },
   {
    title: 'm-m-residence',
    description: "M-M-Residence is a Next.js app that provides guests with details about me and my wife's home listed on HomeExchange.com. Its simple interface is user-friendly and gives guests everything they need to know to have a comfortable and enjoyable stay.",
    image: '/images/5.png',
    tags: ['React.js', 'Next.js', 'MongoDB', 'styled-components'],
    code: 'https://github.com/mihaimazareanu/m-m-residence',
    visit: 'https://m-m-residence.vercel.app/',
    id: 2,
  },
  {
    title: "Mock GPT3-Clone",
    description: "This app is a stunning replica of OpenAI's GPT-3 interface, created with React.js and CSS. Discover how great design can make your app look modern and sleek, using Figma as a design tool. Elevate your app and engage your audience in new and exciting ways.",
    image: '/images/1.png',
    tags: ['React.js', 'CSS', 'Figma'],
    visit: 'https://gpt3-clone-gamma.vercel.app/',
    code: 'https://github.com/mihaimazareanu/gpt3-clone',
    id: 3,
  },
  {
    title: 'Gericht Restaurant',
    description:"This app is a visually appealing mock landing page for a restaurant, designed using Figma and styled with CSS. While it lacks functionality, it serves as an excellent example of the potential for creating modern, engaging web pages with React.js components. Its responsive design ensures accessibility on any device.",
    image: '/images/2.png',
    tags: ['React.js', 'CSS', 'Figma'],
    code: 'https://github.com/mihaimazareanu/gerich-restaurant',
    visit: 'https://gerich-restaurant-omega.vercel.app/',
    id: 4,
  },
  {
    title: 'Modern Business App',
    description: "This React.js app, created using the Vite framework, showcases a modern webpage design for a bank. It features responsive components and efficient build times, providing a seamless user experience. The app serves as an example of modern web design, with a focus on layout and responsiveness.",
      image: '/images/3.png',
      tags: ['React.js', 'Vite', "TailwindCSS", "Figma"],
    code: 'https://github.com/mihaimazareanu/business-modern-app-vite',
    visit: 'https://business-modern-app.vercel.app/',
    id: 5,
  },  
];